language: generic

sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - docker build -t sssuthe/todo-list-server:latest -t sssuthe/todo-list-server:$SHA -f Dockerfile.dev .

script:
  - docker run -e CI=true sssuthe/todo-list-server:latest npm run test -- --coverage


